<?php
 
const DBDRIVE = 'mysql';
const DBHOST = 'localhost';
const DBNAME = 'mk_info';
const DBUSER = 'root';
const DBPASS = '';

const PRIVATE_KEY = <<<EOD
-----BEGIN RSA PRIVATE KEY-----
MIICXAIBAAKBgQCEb6w/T/nJIGERtxBEgKJwCVbAnxTRj7PdXOtHyOt4p5qq9EBW
uwQjKpKusxXxsclfIPqcabHDUBqGNOst8iT4i7T/PMeHuvvNFuB5VTk/PxxrtmOu
EBivO3/SuE4ViTkIv13PgzgkYIYYZXGrTjtiGv3MU6MEHWhEiRnrmE9OmwIDAQAB
AoGAAYYPY0MWSpwWwc9rXn5kYAmbd+fco3SVyywwgMjs/JxhCSp6OwU3zPfGbEAf
NoKnIHMOrxIAO5EGXRjqw8KPblBDuWcAPSfwQmPYv0ZziWvbditgOaDqJH3/S3+B
C80kMKfSjeeUV9GxiNZkS6KSgCK3ziP2WthBZfyoCdbqOpECQQDnvG6MExeBcgPN
GN0tEMFTohvdRbm3uy0cOqJurLFheQFOWwRp61JOSEChlCjr6nflE874hDrRFYHQ
ZIO/S2nnAkEAkk2PFgEeAASU9zqqsF7b1XLVVe1mt4JgzS2X6QVyWgCbeBHTM7Lh
rUiG+9djiEvr1YJ7vLwM/tRgPcr3e0inLQJASvOiWcHvD1oeKp8JIoNR1EgRdR8R
M4Dh1UiNsvg+IwWtS3ea1Ntc8p7h8KDoH23lu30Nq0mxcGDhbNKl3iB5LwJAMqzC
nvCMH512q5uae7SfmHNKCZVNOsriFK9yKrhEP4BuWUxzRzjyij7Q4nJce10wtqeX
jGvmZG3TWBPxXLZxkQJBALVoXooE9debWeGxp1kD/DDUm672sdBDd356dCuQe5gk
3M16M/GnBvddxeq4Hl0Yt+dOp/RXwqISGtbI4NTGIeI=
-----END RSA PRIVATE KEY-----
EOD;

const PUBLIC_KEY = <<<EOD
-----BEGIN PUBLIC KEY-----
MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCEb6w/T/nJIGERtxBEgKJwCVbA
nxTRj7PdXOtHyOt4p5qq9EBWuwQjKpKusxXxsclfIPqcabHDUBqGNOst8iT4i7T/
PMeHuvvNFuB5VTk/PxxrtmOuEBivO3/SuE4ViTkIv13PgzgkYIYYZXGrTjtiGv3M
U6MEHWhEiRnrmE9OmwIDAQAB
-----END PUBLIC KEY-----
EOD;
